---
:ems:
  :ems_nuage:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
        :addition:
          :critical:
          - !ruby/regexp /^nuage_.+_create$/
        :deletion:
          :critical:
          - !ruby/regexp /^nuage_.+_delete$/
        :update:
          :critical:
          - !ruby/regexp /^nuage_.+_update$/
        :status: # alarms
          :critical:
          - !ruby/regexp /^nuage_alarm_.+$/
:http_proxy:
  :nuage:
    :host:
    :password:
    :port:
    :user:
:ems_refresh:
  :nuage_network:
    :allow_targeted_refresh: true
:log:
  :level_nuage: info
:workers:
  :ems_refresh_worker_nuage_network:
    :inherits_from: ems_refresh_worker
  :event_catcher_nuage_network:
    :amqp_connect_timeout: 5.seconds
    :inherits_from: event_catcher
    :topics:
    - topic/CNAMessages
    - topic/CNAAlarms
